### ISSUE TITLE
您好，请问为什么运行玩程序界面一闪而退？

### ISSUE THREAD

**Issue by zhangheng8687** [mkdir700/chaoxing_auto_sign#12]
因为界面一闪而退，所有不知道程序是不是在正常运行，这个是正常现象吗？新人如有冒犯请多谅解。这个是我的配置图，麻烦您帮我看一下哪里出了错误，运行完是没有控制台界面的。
![QQ截图20200330104718](https://user-images.githubusercontent.com/55172641/77870401-e65ecf00-7273-11ea-8f5d-e798c1c2f9a6.png)

**Comment by mkdir700** [comment]
可能是没有安装`requests`模块的缘故
`pip install requests` 安装下这个模块试试吧

**Comment by zhangheng8687** [comment]
> 可能是没有安装`requests`模块的缘故
> `pip install requests` 安装下这个模块试试吧

非常感谢作者如此迅速回复我的疑惑，requests已经安装好了，但是还是没有效果，再次感谢您的回复。

**Comment by mkdir700** [comment]
```python
if __name__ == '__main__':
	try:
		print(local_run())
	except Exception as e:
		print(e)
```
将main下的代码改成这个，抛出下异常，查看下输出内容

**Comment by zhangheng8687** [comment]
是否是我缓存文件地址填写错误？代码改完还是输出日志还是空的 可能是我哪里弄错了
