### ISSUE TITLE
接口问题求助

### ISSUE THREAD

**Issue by villainousx** [mkdir700/chaoxing_auto_sign#15]
我想直接用html直接post接口 每天进一下网页就行了 但是提示
{
    "detail": [
        {
            "loc": [
                "query",
                "username"
            ],
            "msg": "field required",
            "type": "value_error.missing"
        },
        {
            "loc": [
                "query",
                "password"
            ],
            "msg": "field required",
            "type": "value_error.missing"
        }
    ]
}
请问这个怎么解决呀

**Comment by mkdir700** [comment]
![2020/04/03/923f00403084009.png](http://cdn.z2blog.com/2020/04/03/923f00403084009.png)
请求参数正确了吗
如果是手机登录，如图填写就可以了

**Comment by villainousx** [comment]
啊谢谢 发现是忘记改访问方式了 我想用这个接口通过html或者php搭建一个访问就能直接签到的网页?或者能把这个接口改成get吗 不知道虚拟主机能不能实现html或者php的定时计划
