### ISSUE TITLE
对于fastapi的使用我还是很模糊，没有学习过python

### ISSUE THREAD

**Issue by chenaidairong** [mkdir700/chaoxing_auto_sign#16]
我不是很清楚到底该怎么使用fastapi，我已经在脚本中添加了
`from fastapi import FastAPI
app = FastAPI()`
访问的时候他就提升我No operations defined in spec!
没有定义任何操作，具体该怎么做？

**Comment by result-bit** [comment]
可以参考这个仓库https://github.com/result-bit/chaoxing_auto_sign
