### ISSUE TITLE
接口好像挂了诶…

### ISSUE THREAD

**Issue by villainousx** [mkdir700/chaoxing_auto_sign#19]
接口好像挂了诶…

**Comment by mkdir700** [comment]
已修复

**Comment by villainousx** [comment]
老哥…接口提示无签到任务 但是有普通签到没签上

**Comment by mkdir700** [comment]
发下课程id

**Comment by mkdir700** [comment]
发下签到任务的activeid，在签到的链接里面
![image](https://user-images.githubusercontent.com/56359329/79095855-218df180-7d8e-11ea-98d4-f60850dd7289.png)

**Comment by villainousx** [comment]
activeId=194566969
