### ISSUE TITLE
搭建接口出现内部错误

### ISSUE THREAD

**Issue by Qifcn** [mkdir700/chaoxing_auto_sign#21]
(｡･∀･)ﾉﾞ嗨
  你好，我也是饱受签到之苦的普通学生，在b站时候发现了一款可以签到的程序，不过部署还是未成功，不过在Github搜索时候难以置信还是有优秀的人开源签到代码。在搭建接口的时候我遇到了一点小麻烦，望作者能帮助到我。

## 问题
搭建成功后也可以访问```FastAPI```界面，在测试是否成功的时候出现了以下情况
![image](https://user-images.githubusercontent.com/34029055/78988319-33d81780-7b63-11ea-99b6-7f50ead37ebb.png)
相应的后台也出现了报错
![image](https://user-images.githubusercontent.com/34029055/78988384-5e29d500-7b63-11ea-9947-6554093cdd4b.png)
我是按照作者的教程开始搭建的
### 资源
阿里云服务器
乌班图18.6版本系统
python3.6
### 搭建步骤
```
1. git clone https://github.com/mkdir700/chaoxing_auto_sign.git
2. cd chaoxing_auto_sign
3. pip3 install -r requirements.txt

然后运行起这个实例

```
都是默认自带的
pip install -r requirements.txt会报错误如下
![image](https://user-images.githubusercontent.com/34029055/78988809-8403a980-7b64-11ea-8871-f2417a1206d3.png)
浏览器访问https://passport2.chaoxing.com/api/login?name=账号&pwd=密码&schoolid=&verify=0如下
![image](https://user-images.githubusercontent.com/34029055/78988863-a5fd2c00-7b64-11ea-9083-7667806e0a21.png)

**Comment by mkdir700** [comment]
谢谢你的支持！
按你的问题顺序，我的建议如下：
1、修改脚本，在第119行下方，添加一行`print(r.text)`，如图所示 我需要知道请求登录后，返回的信息是什么
![image](https://user-images.githubusercontent.com/56359329/78990939-499d0b00-7b6a-11ea-8b19-5b94e84f68b0.png)

2、这个问题暂时不知道怎么回事

**Comment by mkdir700** [comment]
创建一个python3.7 的虚拟环境试试吧

**Comment by Qifcn** [comment]
你好作者，或许已经找到原因了，是因为猫厂和鹅厂的ip可能被拉黑的缘故
