### ISSUE TITLE
几个小建议（自己在测试代码的发现一点小问题）

### ISSUE THREAD

**Issue by Ircon** [mkdir700/chaoxing_auto_sign#22]
# 几个小问题
感谢 @mkdir700 的贡献，这里发现几个小问题，请教一下。
## 第一个关于 Cookie 是否有效的测试
```python
r = self.session.get('http://i.mooc.chaoxing.com/app/myapps.shtml',allow_redirects=False)
if r.status_code != 200:
    print("cookies已失效")
    return False
else:
    print("cookies有效哦")
    return True
```
源代码中采用如上方法。但是在我的测试中，发现这个方法并不有效，因为我人工改了cookie之后，再次登录，返回的状态码依旧是200，但是返回的界面变了。

## 签到类型的判定
原代码中是通过`id= startList`，签到的div里面的文字。但是我通过`id = endList`里面的内容，发现这个文字似乎是能改的。具体怎样无法确定，现在手上没有教师账号没法测试。
我猜测可以通过`onclick`对应的`activeDetail`方法的第二参数判断。

## 如何获取照片上传的token？
在其他issue中，提及了如何上传照片。但是那个token应该你的。如何使用自己的获取自己的token呢？

## 请问一下如何测试的？
由于没有教师发布点到任务，我在的一些猜测无法测试。所以请教一下如何测试？自己注册一个教师账号吗？

## 其他小问题
- 手势签到和二维码签到都是前端判定吗？
- 是否不使用cookie更佳？超星的cookie判定似乎有问题，或许不使用，可以提高一点容错性。

**以上内容可能不是完全正确的。部分场景无法测试，只是猜测。**

**Comment by yuban10703** [comment]
测试cookie貌似可以用这个url测试https://sso.chaoxing.com/apis/login/userLogin4Uname.do

这个貌似是获取完整cookie用的
贴上部分代码,,,
session = requests.session()
parameter={}
def parameter():
    with open('account.json', 'r') as f:
        parameter = json.load(f)
        print('获取配置成功')
        return parameter
def login(username, passwd):  # 获取cookie
    try:
        with open("cookie.json",'r') as load_f:
            print('有cookie文件')
            cookie = json.load(load_f)
            check_url = 'https://sso.chaoxing.com/apis/login/userLogin4Uname.do'
            res = requests.get(check_url, cookies=cookie)
            cdata = json.loads(res.text)
            if (cdata['result'] != 1):
                print('cookie失效')
                raise Exception('cookie失效')
            else:
                print('cookie有效')
            # respon = res.status_code
            # print(respon)

    except:
        print('未找到cookie文件或cookie失效')
        url = 'https://passport2-api.chaoxing.com/v11/loginregister'
        data = {'uname': username, 'code': passwd, }
        cookie_jar = session.post(url=url, data=data, ).cookies
        cookie = requests.utils.dict_from_cookiejar(cookie_jar)
        with open("cookie.json", "w") as f:
            json.dump(cookie, f)
            print("获取cookie完成")
    finally:
        return cookie

**Comment by yuban10703** [comment]
获取token可以用这个
```
    def token(self):  # 获取上传图片用的token
        url = 'https://pan-yz.chaoxing.com/api/token/uservalid'
        res = requests.get(url, headers=headers, cookies=cook[0])
        tokendict = json.loads(res.text)
        return (tokendict['_token'])
```

**Comment by Ircon** [comment]
我现在写的一个新的Py程序，没有测试cookie。直接用账号密码登录。因为总是感觉使用cookie不稳定。而且流程上简化了很多。
```python
import requests
import re
from bs4 import BeautifulSoup

# 用于连接的连接
Url_Dic = {

	'log':'https://passport2.chaoxing.com/api/login?name={}&pwd={}&verify=0',
	'course':'http://mooc1-api.chaoxing.com/mycourse/backclazzdata?view=json&rss=1',
	'action':'http://mobilelearn.chaoxing.com/widget/pcpick/stu/index?courseId={}&jclassId={}',
	'sign':'https://mobilelearn.chaoxing.com/pptSign/stuSignajax'
}

#报文的头部
Http_Header = {
	'Accept-Encoding': 'gzip, deflate',
	'Accept-Language': 'zh-CN,zh;q=0.9',
	'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
	'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.100 Safari/537.36'
}


def Log(sess,user,pwd) -> tuple:
	'''
	登录
	:param sess: 会话的对象
	:param user: 用户名，注意这个用户名注释学校登录的用户名
	:param pwd: 用户密码

	:return tuple: uid和fid，后面签到时候要用到
	'''
	req = sess.get(Url_Dic['log'].format(user,pwd),headers = Http_Header)
	if req.status_code == 200 :
		statu = req.json()
		if statu['result'] == True:
			return (req.cookies['UID'],req.cookies['fid'])
		else:
			# 没有登录成功
			return None
	else:
		# 状态码错误
		return None

def Get_Course(sess) -> dict:
	'''
	获取所有的课程的 class id 和 course id
	:param sess: 会话对象
	:return dict: key->课程名字 val -> 两个id
	'''
	req = sess.get(Url_Dic['course'],headers = Http_Header)
	if req.status_code == 200:
		jsn = req.json()
		if (jsn['result'] == 1) and (jsn['msg'] == '获取成功'):
			jsn = jsn['channelList']
			dic = {}
			for ele in jsn:
				context = ele['content']
				class_id = context['id']
				
				# 有可能是助教
				if'course' not in context:
					continue
				
				context = context['course']['data'][0]
				name = context['name']
				course_id = context['id']
				dic[name] = (class_id,course_id)			
			return dic
		else:
			# 没有获取成功
			return None
	else:
		# 状态码错误
		return None

def Get_ActionCode(sess,courseId,classId) -> list:
	'''
	获取签到的activeID
	:params sess: 会话对象
	:params courseId: 课程ID
	:params classId: 班级ID \n
	:return list: 此班级此课程的ActiveId（签到可能不止一个）
	'''
	req = sess.get(Url_Dic['action'].format(courseId,classId),headers = Http_Header)
	if req.status_code == 200:
		bs = BeautifulSoup(req.text,'html.parser')
		tag_list = bs.findAll('div',id = 'startList')
		if tag_list == None or len(tag_list) != 1 : #获取的网页有问题
			return None
		# print(tag_list)
		action_list = []
		for child in tag_list[0].children:
			if child.name == None: #防止空白字符
				continue

			#获取标签的类型防止不是签到
			ty = child.findAll('dd',class_='green')[0].text
			if ty == '签到':
				# 获取action码
				action = (child.findAll('div',class_ = 'Mct')[0]['onclick'])
				action = re.findall(r'\(\d+,',action)[0]
				action = action.lstrip('(')
				action = action.rstrip(',')
				action_list.append(action)
			
		return action_list
	else:
		return None
def Sign(sess,activeId,uid,fid) -> tuple:
	'''进行签到。
	普通签到，手势签到，二维码签到，只需要访问特定url即可。
	地点的签到需要额外附加address参数，这个参数可以随意填。
	照片签到需要使用objectID，这里直接用一个完全黑色的图片代替。
	:params sess: 会话对象
	:params activeId: 签到的id
	:params uid: 登录时候Cookice里面的uid
	:params fid: 登录时候Cookice里面的fid
	:return tuple: 登录结果，(boolean,string)，一个代表是否签到成功，第二代表状态
	'''
	param = {
		'name':'',
		'activeId':activeId,
		'address': '中国',
		'objectId':'6a8df24eb46a0c5feea3e95a6e3ec15d',#图片签到，这个是一张全黑的图片
		'uid': uid,
		'clientip': '0.0.0.0',
		'latitude': '-2',
		'longitude': '-1',
		'fid': fid,
		'appType': '15',
		'ifTiJiao': '1'
	}
	req = sess.get(Url_Dic['sign'],params = param)
	if req.status_code == 200:
		if req.text == 'success':
			return (True,req.text)
		else:
			return (False,req.text)
	else:
		return (False,'statu code is worry')

if __name__ == '__main__':
	user = '账号'
	pwd = '密码'

	sess = requests.session()
	ufid = Log(sess,user,pwd)
	dic = Get_Course(sess)

	for key,val in dic.items() :
		print(f'课程名字: {key} class id:{val[0]}, course id:{val[1]}')
		actions = Get_ActionCode(sess,val[1],val[0])
		if actions != None and len(actions) > 0:
			for code in actions:
				print(Sign(sess,code,ufid[0],ufid[1]))
		else:
			print('没有签到')
```

**Comment by Ircon** [comment]
> 获取token可以用这个
> 
> ```
>     def token(self):  # 获取上传图片用的token
>         url = 'https://pan-yz.chaoxing.com/api/token/uservalid'
>         res = requests.get(url, headers=headers, cookies=cook[0])
>         tokendict = json.loads(res.text)
>         return (tokendict['_token'])
> ```

其实我感觉，一个纯黑的照片解决一切。 😂

**Comment by yuban10703** [comment]
啊!,是我火星了,原来不用cookie也可以签到,,,,,,,,,,,,,,

**Comment by Ircon** [comment]
> 啊!,是我火星了,原来不用cookie也可以签到,,,,,,,,,,,,,,

超星的手机端写的十分随意，基本上不加密。

**Comment by yuban10703** [comment]
![image](https://user-images.githubusercontent.com/39484884/79826906-86b99680-83cf-11ea-9355-3d4baffd0a12.png)

判断签到的话,最下面这个url里应该可以判断吧,我太菜了,不会弄...........

**Comment by yuban10703** [comment]
还有,可以自己开个课程测试,不用老师账号来着.............

**Comment by Ircon** [comment]
> ![image](https://user-images.githubusercontent.com/39484884/79826906-86b99680-83cf-11ea-9355-3d4baffd0a12.png)
> 
> 判断签到的话,最下面这个url里应该可以判断吧,我太菜了,不会弄...........

的确使用最后这个就可以。
对于非照相签到，只需要 activeid uid fid，即可。
但是对于照相签到，需要额外添加一个 objectId。
这个objectId，可以通过token提交图片之后获取。

**Comment by Ircon** [comment]
> 还有,可以自己开个课程测试,不用老师账号来着.............

这个似乎各个学校不同。
超星似乎允许各个学校使用自己的接口进行二次搭建。
我们学校账号登录之后会跳转到`chaoxing.学校名字简写.edu.cn`的页面。通过这个页面进入学习空间后，我找了一下，但是没有对应的自己创建课程的入口。

**Comment by yuban10703** [comment]
![image](https://user-images.githubusercontent.com/39484884/79827480-fa0fd800-83d0-11ea-8ac5-c32b4ffd3c29.png)
我这里进空间之后可以开课,emmmmm

**Comment by Ircon** [comment]
我发一下我的思路。

- 登录使用

    ```
    https://passport2.chaoxing.com/api/login?name={}&pwd={}&verify=0
    ```

    无需加密，返回值为JSON

- 访问课程列表

    ```
    http://mooc1-api.chaoxing.com/mycourse/backclazzdata?view=json&rss=1
    ```

    无需参数，直接可用，返回的数据是JSON。

    这一步需要提取ClassID 和 CourseID。
    CourseID为`content/course/data[0]/id`
    ClassID 为`content/id`

- 访问签到网页获取actionID

    ```
    http://mobilelearn.chaoxing.com/widget/pcpick/stu/index?courseId={}&jclassId={}
    ```

    需要确认两个部分一个是否是签到，因为有其他任务也在哪个网页。这个需要检查`<dd class='green'>`这个标签的内容。
    另外一个是这个签到的`actionID`，这个需要通过`onclick`触发的`activeDetail`的第一个参数获取。

- 签到

    ````
    https://mobilelearn.chaoxing.com/pptSign/stuSignajax
    ````

    访问这个网址并使用这些参数

    ```
    {
        'name':'',
        'activeId':你之前获取的,
        'address': '中国',
        'objectId':'6a8df24eb46a0c5feea3e95a6e3ec15d',//照片ID
        'uid': 登录时候cookie里面的,
        'clientip': '0.0.0.0',
        'latitude': '-2',
        'longitude': '-1',
        'fid': 登录时候cookie里面的,
        'appType': '15',
        'ifTiJiao': '1'
    }
    ```

**Comment by Ircon** [comment]
> ![image](https://user-images.githubusercontent.com/39484884/79827480-fa0fd800-83d0-11ea-8ac5-c32b4ffd3c29.png)
> 我这里进空间之后可以开课,emmmmm

![image](https://user-images.githubusercontent.com/11171522/79827622-65f24080-83d1-11ea-81bb-d50976dd276a.png)
我点击添加之后直接跳转到我们学校域名下另一个页面。
只能自己选择已有的课程。

**Comment by yuban10703** [comment]
emmm

**Comment by yuban10703** [comment]
我想刷超星这个小花的,但是不知道它的使用次数和阅读时间是怎么计算的.....
![image](https://user-images.githubusercontent.com/39484884/79828049-79ea7200-83d2-11ea-8be8-87946fe39956.png)

**Comment by yuban10703** [comment]
> 我想刷超星这个小花的,但是不知道它的使用次数和阅读时间是怎么计算的.....
> ![image](https://user-images.githubusercontent.com/39484884/79828049-79ea7200-83d2-11ea-8be8-87946fe39956.png)

码好像白打了....不管了.......

**Comment by Ircon** [comment]
> 我想刷超星这个小花的,但是不知道它的使用次数和阅读时间是怎么计算的.....
> 
> ![image](https://user-images.githubusercontent.com/39484884/79828158-bae28680-83d2-11ea-9850-9305c3bea108.png)

这个就不知道了，没研究过。

**Comment by mkdir700** [comment]
cookies校验问题：
之前想的是访问某一个需要cookie的链接，然后不让他自动`allow_redirects=False`跳转
以此来判断其状态码，如果状态码不是200，就是失效。
看了下确实有bug存在，现在更新了，检测访问`http://notice.chaoxing.com/pc/notice/getUnitList`

签到类型的判定
这个查看了下，确实有问题。
通过`activeDetail(209779810,2,null)` 这个也不能判断出具体的签到类型，`2`统一代表的签到
我想的是多请求一次，进入签到页查看是什么签到类型

如何获取照片上传的token？
这个最新版本的本地脚本，已经更新了。将图片上传到image文件夹内，拍照签到时，会随机选择一张，token是根据cookie请求来的

请问一下如何测试的？
可以自己创建一门课程，借用同学的账号，加入班级

其他小问题
手势签到和二维码签到都是前端判定吗？
手势签到，其实是按照
1 2 3
4 5 6
7 8 9
九宫格，连成线之后，相当于就是一个数字验证码，好像是js实现的，请求接口的时候，是数字验证码。因为签到都是直接通过api无任何验证，请求一次就完成了，这个也没深究

是否不使用cookie更佳？超星的cookie判定似乎有问题，或许不使用，可以提高一点容错性。
这个没试过，只要有登录之后的才进行的操作，个人还是觉得带上cookie保证有效性

**Comment by Ircon** [comment]
> ##cookies校验问题：
> 之前想的是访问某一个需要cookie的链接，然后不让他自动`allow_redirects=False`跳转
> 以此来判断其状态码，如果状态码不是200，就是失效。
> 看了下确实有bug存在，现在更新了，检测访问`http://notice.chaoxing.com/pc/notice/getUnitList`
> 
> ##签到类型的判定
> 这个查看了下，确实有问题。
> 通过`activeDetail(209779810,2,null)` 这个也不能判断出具体的签到类型，`2`统一代表的签到
> 我想的是多请求一次，进入签到页查看是什么签到类型
> 
> ##如何获取照片上传的token？
> 这个最新版本的本地脚本，已经更新了。将图片上传到image文件夹内，拍照签到时，会随机选择一张，token是根据cookie请求来的
> 
> ##请问一下如何测试的？
> 可以自己创建一门课程，借用同学的账号，加入班级
> 
> ##其他小问题
> 手势签到和二维码签到都是前端判定吗？
> 手势签到，其实是按照
> 1 2 3
> 4 5 6
> 7 8 9
> 九宫格，连成线之后，相当于就是一个数字验证码，好像是js实现的，请求接口的时候，是数字验证码。因为签到都是直接通过api无任何验证，请求一次就完成了，这个也没深究
> 
> 是否不使用cookie更佳？超星的cookie判定似乎有问题，或许不使用，可以提高一点容错性。
> 这个没试过，只要有登录之后的才进行的操作，个人还是觉得带上cookie保证有效性

感谢解答，最后提一个小问题。
在获取activeID的时候，在任务界面可能不止有签到活动，还有诸如作业之类的任务。所以获取activeID之外，还是需要判断一下这个activeID是不是一个签到的。

我的方法是判断这里。这个地方比较有标识性。
![image](https://user-images.githubusercontent.com/11171522/79934138-67307580-8484-11ea-9355-ae29905034a2.png)

**Comment by mkdir700** [comment]
签到好判断，签到类型只能多做一步，进入到签到界面

**Comment by mkdir700** [comment]
获取activeid的时候，后面的参数是2就是，签到任务
我用正则筛选出来了

**Comment by Ircon** [comment]
> 获取activeid的时候，后面的参数是2就是，签到任务
> 我用正则筛选出来了

😂谢谢回答

**Comment by mkdir700** [comment]
交流经验，O(∩_∩)O哈哈~
