### ISSUE TITLE
总是显示暂无签到任务

### ISSUE THREAD

**Issue by q4q3q9q9** [mkdir700/chaoxing_auto_sign#23]
原先能够正常使用，在差不多两周以前无法正常使用，有签到任务也显示暂无签到任务，在今天更新并重新配置之后，在显示完课程ID和名称之后没有返回直接退出，运行显示如下：[https://cloud.q4q3q9q9.top/index.php/s/RqN5xdm7kCEftBD](url)
当时想签到的activeID：209586833
配置区只填了server酱和手机账号密码，不太知道是哪里出错了........

**Comment by mkdir700** [comment]
没有返回信息，是因为方法返回值，返回来之后没有被打印
之前本地脚本慢慢写成api了，所以这个没改过来，现在已经修改了
可以在你现在脚本的基础上，修改这个方法
```python
def local_run():
    if DEBUG:
        debug()
    else:
        gen_run()
```
更改为
```python
def local_run():
    if DEBUG:
        print(debug())
    else:
        print(gen_run())
```

**Comment by q4q3q9q9** [comment]
OK，测试已解决，感谢回复。
另问一下，大概在什么情况下需要配置IP和位置？

**Comment by mkdir700** [comment]
这个配不配置都可以，如果自己需求就用，不用就默认就行了
我一般就是直接默认的
