### ISSUE TITLE
版权问题

### ISSUE THREAD

**Issue by Closty** [mkdir700/chaoxing_auto_sign#27]
作者您好，我已在您的基础上更改代码实现无服务运行，并已附上您的github地址信息，如果版权有处理不好之处，请予以指点！谢谢您！
地址：[https://github.com/Closty/chaoxing](https://github.com/Closty/chaoxing)

**Comment by mkdir700** [comment]
互相交流

**Comment by mkdir700** [comment]
加油

**Comment by Closty** [comment]
谢谢
