### ISSUE TITLE
bug提交

### ISSUE THREAD

**Issue by nymanyim** [mkdir700/chaoxing_auto_sign#31]
发现有账号存在获取不了课程签到的情况，其他账号测试正常。部分账号获取不了课程签到，显示无签到任务，问题账号已发大大的谷歌邮箱，希望看一下什么情况

**Comment by mkdir700** [comment]
已收到

**Comment by yt132** [comment]
为什么我搭建了api然后返回“登录失败，拒绝访问"code:1002
