### ISSUE TITLE
linux菜鸟一枚，问一下如何部署

### ISSUE THREAD

**Issue by tomlongcool** [mkdir700/chaoxing_auto_sign#32]
直接 pip i -r requiremnts.txt就好了么

**Comment by chenaidairong** [comment]
已经提交了一个自动脚本，可以尝试一下

**Comment by chenaidairong** [comment]
> 直接pip i -r requiremnts.txt就好了么

我已经提交了一个自动脚本，可以尝试一下|
自动内容有：安装screen，python3，依赖安装，以及运行
