### ISSUE TITLE
只显示脚本已开始运行

### ISSUE THREAD

**Issue by q4q3q9q9** [mkdir700/chaoxing_auto_sign#33]
只显示脚本已开始运行，有cookies生成，没有ActiveID生成，界面没反应，只能controlC
[root@instance-8 q4q3q9q9]# python3 cx.py
脚本已开始运行
^CTraceback (most recent call last):
  File "cx.py", line 454, in <module>
    scheduler.start()
  File "/usr/local/lib/python3.6/site-packages/apscheduler/schedulers/blocking.py", line 19, in start
    self._main_loop()
  File "/usr/local/lib/python3.6/site-packages/apscheduler/schedulers/blocking.py", line 28, in _main_loop
    self._event.wait(wait_seconds)
  File "/usr/lib64/python3.6/threading.py", line 551, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib64/python3.6/threading.py", line 299, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
请问是我Python环境出问题了吗？
依赖已经安装（就是每安装一个依赖就说一次没有wheel报错）
Python3.6.8，pip20.1

**Comment by mkdir700** [comment]
默认是5分钟执行一次签到任务
修改452行的代码,可以自定义执行间隔

**Comment by q4q3q9q9** [comment]
就是说，没有输出是正常情况，有签到任务的时候就有输出呗？
（主要是脚本有没有自动检查没反馈，怕错过签到....)

**Comment by mkdir700** [comment]
运行就只有一个"脚本开始执行" 吗
正常的话,会显示cookie是否有效,以及课程列表

**Comment by q4q3q9q9** [comment]
是的，跑起来全部日志如上
那多半就是我Python环境有问题.....
GCP香港地区服务器，原先可以正常签到（但是签到检查确实不稳定，api版本没有问题）

**Comment by yuhangrao** [comment]
相同情况，配置完后只输出脚本已开始运行，server酱配置了也没有消息推送，CTRL+c结束后显示如下：
[root@iZbp127o02jeggio3jikzkZ local]# python local_sign.py
脚本已开始运行
^CTraceback (most recent call last):
  File "local_sign.py", line 454, in <module>
    scheduler.start()
  File "/usr/local/lib/python3.6/site-packages/apscheduler/schedulers/blocking.py", line 19, in start
    self._main_loop()
  File "/usr/local/lib/python3.6/site-packages/apscheduler/schedulers/blocking.py", line 28, in _main_loop
    self._event.wait(wait_seconds)
  File "/usr/lib64/python3.6/threading.py", line 551, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib64/python3.6/threading.py", line 299, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
没有显示cookie是否有效和课程列表，（配置好第一次运行

**Comment by mkdir700** [comment]
运行后, 间隔5分钟才会开始执行
可以自行修改缩短时间
修改452行的代码

**Comment by mkdir700** [comment]
> 相同情况，配置完后只输出脚本已开始运行，server酱配置了也没有消息推送，CTRL+c结束后显示如下：
> [root@iZbp127o02jeggio3jikzkZ local]# python local_sign.py
> 脚本已开始运行
> ^CTraceback (most recent call last):
> File "local_sign.py", line 454, in
> scheduler.start()
> File "/usr/local/lib/python3.6/site-packages/apscheduler/schedulers/blocking.py", line 19, in start
> self._main_loop()
> File "/usr/local/lib/python3.6/site-packages/apscheduler/schedulers/blocking.py", line 28, in _main_loop
> self._event.wait(wait_seconds)
> File "/usr/lib64/python3.6/threading.py", line 551, in wait
> signaled = self._cond.wait(timeout)
> File "/usr/lib64/python3.6/threading.py", line 299, in wait
> gotit = waiter.acquire(True, timeout)
> KeyboardInterrupt
> 没有显示cookie是否有效和课程列表，（配置好第一次运行

运行后, 间隔5分钟才会开始执行
可以自行修改缩短时间
修改452行的代码

**Comment by yuhangrao** [comment]
> > 相同情况，配置完后只输出脚本已开始运行，server酱配置了也没有消息推送，CTRL+c结束后显示如下：
> > [root@iZbp127o02jeggio3jikzkZ local]# python local_sign.py
> > 脚本已开始运行
> > ^CTraceback (most recent call last):
> > File "local_sign.py", line 454, in
> > scheduler.start()
> > File "/usr/local/lib/python3.6/site-packages/apscheduler/schedulers/blocking.py", line 19, in start
> > self._main_loop()
> > File "/usr/local/lib/python3.6/site-packages/apscheduler/schedulers/blocking.py", line 28, in _main_loop
> > self._event.wait(wait_seconds)
> > File "/usr/lib64/python3.6/threading.py", line 551, in wait
> > signaled = self._cond.wait(timeout)
> > File "/usr/lib64/python3.6/threading.py", line 299, in wait
> > gotit = waiter.acquire(True, timeout)
> > KeyboardInterrupt
> > 没有显示cookie是否有效和课程列表，（配置好第一次运行
> 
> 运行后, 间隔5分钟才会开始执行
> 可以自行修改缩短时间
> 修改452行的代码

谢谢，我已经知道了这个问题，但现在脚本开始运行后提示登陆信息有误登陆失败，但我反复检查username和password都没有错误，可以在学习通登录，手机号登陆没有schoolID，不知道是怎么回事。我写的是：
USER_INFO = {
    'username': 'example',
    'password': 'example_password',
    'schoolid': ''  # 学号登录才需要填写
}

**Comment by mkdir700** [comment]
> > > 相同情况，配置完后只输出脚本已开始运行，server酱配置了也没有消息推送，CTRL+c结束后显示如下：
> > > [root@iZbp127o02jeggio3jikzkZ local]# python local_sign.py
> > > 脚本已开始运行
> > > ^CTraceback (most recent call last):
> > > File "local_sign.py", line 454, in
> > > scheduler.start()
> > > File "/usr/local/lib/python3.6/site-packages/apscheduler/schedulers/blocking.py", line 19, in start
> > > self._main_loop()
> > > File "/usr/local/lib/python3.6/site-packages/apscheduler/schedulers/blocking.py", line 28, in _main_loop
> > > self._event.wait(wait_seconds)
> > > File "/usr/lib64/python3.6/threading.py", line 551, in wait
> > > signaled = self._cond.wait(timeout)
> > > File "/usr/lib64/python3.6/threading.py", line 299, in wait
> > > gotit = waiter.acquire(True, timeout)
> > > KeyboardInterrupt
> > > 没有显示cookie是否有效和课程列表，（配置好第一次运行
> > 
> > 
> > 运行后, 间隔5分钟才会开始执行
> > 可以自行修改缩短时间
> > 修改452行的代码
> 
> 谢谢，我已经知道了这个问题，但现在脚本开始运行后提示登陆信息有误登陆失败，但我反复检查username和password都没有错误，可以在学习通登录，手机号登陆没有schoolID，不知道是怎么回事。我写的是：
> USER_INFO = {
> 'username': 'example',
> 'password': 'example_password',
> 'schoolid': '' # 学号登录才需要填写
> }

重新更新了下, 下载新版本,试试看

**Comment by q4q3q9q9** [comment]
OK，问题已解决，感谢回复
