### ISSUE TITLE
检测cookies是否失效的api，在我这里测试，无论cookies是否有效，status都会返回true

### ISSUE THREAD

**Issue by NullFullme** [mkdir700/chaoxing_auto_sign#35]
并且不导入cookies作为参数，经测试，也是返回true

**Comment by mkdir700** [comment]
cookie为空的情况下,默认使用配置好的账号密码

**Comment by NullFullme** [comment]
作者你好，我是直接使用api插件测试请求的，测试后“http://notice.chaoxing.com/pc/notice/getUnitList”这个接口确实有点异常，请您看下下面我的截图
![image](https://user-images.githubusercontent.com/25143331/83725907-4eb39d80-a675-11ea-9f48-39f476995d6c.png)

**Comment by NullFullme** [comment]
![image](https://user-images.githubusercontent.com/25143331/83726136-aa7e2680-a675-11ea-9a1a-3219f8b8d510.png)

**Comment by mkdir700** [comment]
好的 晚上改下, api版本上次修改过这个地方,本地脚本忘改了

**Comment by mkdir700** [comment]
感谢反馈
