### ISSUE TITLE
二维码签到失败

### ISSUE THREAD

**Issue by johnpoint** [mkdir700/chaoxing_auto_sign#38]
二维码签到显示扫描失败

**Comment by Anthonyfhd** [comment]
我也是

**Comment by DoffChen** [comment]
+1

**Comment by Xy2002** [comment]
我也是

**Comment by 1500931293** [comment]
都是这样 学习通官方更新了签到接口

**Comment by mkdir700** [comment]
我先重新抓包看下接口

**Comment by eco-re** [comment]
bug能修复吗？超星好像改了机制？

**Comment by mkdir700** [comment]
初步看了下，官方在原来的基础上多加了一个验证字段 `enc`
这个`enc`字段来自二维码，将二维码解码后就可以拿到了。
明天还要上班，明天晚上有时间改改吧

**Comment by mkdir700** [comment]
> bug能修复吗？超星好像改了机制？

二维码直接签到好像没办法了，必须要拿到二维码才行。

**Comment by 1500931293** [comment]
> 
> 
> > bug能修复吗？超星好像改了机制？
> 
> 二维码直接签到好像没办法了，必须要拿到二维码才行。

那如果拿到的是10s一换的二维码 过期了，有没有什么方法能签

**Comment by BapiGso** [comment]
> > bug能修复吗？超星好像改了机制？
> 
> 二维码直接签到好像没办法了，必须要拿到二维码才行。

enc可以通过get这个接口https://mobilelearn.chaoxing.com/v2/apis/sign/refreshQRCode?附上activeId得到

**Comment by Shine-H** [comment]
期待。

**Comment by BapiGso** [comment]
> 期待。

活动创建人才能验证请求，刚刚我弄错了，不好意思

**Comment by mkdir700** [comment]
> > 期待。
> 
> 活动创建人才能验证请求，刚刚我弄错了，不好意思

哈哈哈，昨天我也是，我想直接通过这个接口拿，然后请求了，突然想起，这得创建者身份才能访问。

**Comment by xiaofengv233** [comment]
请问拿到二维码了  十秒刷新一次的怎么签到？

**Comment by mkdir700** [comment]
> 请问拿到二维码了 十秒刷新一次的怎么签到？

能拿到二维码的话，可以将二维码解码，其中就有关键字`enc`

关键就是这个`enc`参数，动态二维码，`enc`依然是不变的。

所以只要拿到一张二维码，解码获取其`enc`值就行了

**Comment by johnpoint** [comment]
问题是要拿到二维码
都拿到二维码的权限学生时没有的

**Comment by mkdir700** [comment]
> 问题是要拿到二维码 都拿到二维码的权限学生时没有的
> […](#)
> On Dec 7 2020, at 7:23 pm, mkdir700 ***@***.***> wrote: > 请问拿到二维码了 十秒刷新一次的怎么签到？ 能拿到二维码的话，可以将二维码解码，其中就有关键字enc 关键就是这个enc参数，动态二维码，enc依然是不变的。 所以只要拿到一张二维码，解码获取其enc值就行了 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub ***@***.***/0?redirect=https%3A%2F%2Fgithub.com%2Fmkdir700%2Fchaoxing_auto_sign%2Fissues%2F38%23issuecomment-739856336&recipient=cmVwbHkrQUY1UkVZQTRGQzRLNlIzR1lRVFFTSlY1M0hZMzdFVkJOSEhDWktOUUpJQHJlcGx5LmdpdGh1Yi5jb20%3D), or unsubscribe ***@***.***/1?redirect=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAF5REYEXU5WEYCUNYCQTLWDSTS3L7ANCNFSM4UAKXBGQ&recipient=cmVwbHkrQUY1UkVZQTRGQzRLNlIzR1lRVFFTSlY1M0hZMzdFVkJOSEhDWktOUUpJQHJlcGx5LmdpdGh1Yi5jb20%3D).

嗯，就是不知道怎么拿二维码，只有创建者权限才能获取二维码。😥

**Comment by xiaofengv233** [comment]
> > 问题是要拿到二维码 都拿到二维码的权限学生时没有的
> > […](#)
> > On Dec 7 2020, at 7:23 pm, mkdir700 _**@**_._**> wrote: > 请问拿到二维码了 十秒刷新一次的怎么签到？ 能拿到二维码的话，可以将二维码解码，其中就有关键字enc 关键就是这个enc参数，动态二维码，enc依然是不变的。 所以只要拿到一张二维码，解码获取其enc值就行了 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub _**@**_.**_/0?redirect=https%3A%2F%2Fgithub.com%2Fmkdir700%2Fchaoxing_auto_sign%2Fissues%2F38%23issuecomment-739856336&recipient=cmVwbHkrQUY1UkVZQTRGQzRLNlIzR1lRVFFTSlY1M0hZMzdFVkJOSEhDWktOUUpJQHJlcGx5LmdpdGh1Yi5jb20%3D), or unsubscribe _**@**_.***/1?redirect=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAF5REYEXU5WEYCUNYCQTLWDSTS3L7ANCNFSM4UAKXBGQ&recipient=cmVwbHkrQUY1UkVZQTRGQzRLNlIzR1lRVFFTSlY1M0hZMzdFVkJOSEhDWktOUUpJQHJlcGx5LmdpdGh1Yi5jb20%3D).
> 
> 嗯，就是不知道怎么拿二维码，只有创建者权限才能获取二维码。😥

就是说现在有二维码，我们也不能签？十秒刷新的那个

**Comment by TicklTock** [comment]
> > > 问题是要拿到二维码 都拿到二维码的权限学生时没有的
> > > […](#)
> > > On Dec 7 2020, at 7:23 pm, mkdir700 _**@**_._**> wrote: > 请问拿到二维码了 十秒刷新一次的怎么签到？ 能拿到二维码的话，可以将二维码解码，其中就有关键字enc 关键就是这个enc参数，动态二维码，enc依然是不变的。 所以只要拿到一张二维码，解码获取其enc值就行了 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub _**@**_.**_/0?redirect=https%3A%2F%2Fgithub.com%2Fmkdir700%2Fchaoxing_auto_sign%2Fissues%2F38%23issuecomment-739856336&recipient=cmVwbHkrQUY1UkVZQTRGQzRLNlIzR1lRVFFTSlY1M0hZMzdFVkJOSEhDWktOUUpJQHJlcGx5LmdpdGh1Yi5jb20%3D), or unsubscribe _**@**_.***/1?redirect=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAF5REYEXU5WEYCUNYCQTLWDSTS3L7ANCNFSM4UAKXBGQ&recipient=cmVwbHkrQUY1UkVZQTRGQzRLNlIzR1lRVFFTSlY1M0hZMzdFVkJOSEhDWktOUUpJQHJlcGx5LmdpdGh1Yi5jb20%3D).
> > 
> > 
> > 嗯，就是不知道怎么拿二维码，只有创建者权限才能获取二维码。😥
> 
> 就是说现在有二维码，我们也不能签？十秒刷新的那个

有二维码是可以签到的，发布活动以后enc参数不会变，enc参数应该只和活动ID有关，但是现在没办法知道超星的加密方式

**Comment by MJscofield** [comment]
如果顺利拿到enc参数的话要如何签到？请求哪个接口

**Comment by mkdir700** [comment]
> 如果顺利拿到enc参数的话要如何签到？请求哪个接口

刚更新，原签到接口新增enc字段

**Comment by MJscofield** [comment]
好的 感谢
