### ISSUE TITLE
问一下大佬local下的脚本为什么用云函数运行不了

### ISSUE THREAD

**Issue by 1500931293** [mkdir700/chaoxing_auto_sign#39]
写入腾讯云函数运行失败

**Comment by mkdir700** [comment]
发下运行日志

**Comment by 1500931293** [comment]
返回数据:

{"errorCode":-1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python3/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python3/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 172, in load_source\n    module = _load(spec)\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 675, in _load\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 655, in _load_unlocked\n  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 678, in exec_module\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 205, in _call_with_frames_removed\n  File \"/var/user/index.py\", line 9, in \u003cmodule\u003e\n    from lxml import etree\nModuleNotFoundError: No module named 'lxml'"}

日志:

START RequestId: 7cac85e2-4bf7-42eb-a1ce-26dd4c61fe3d

Event RequestId: 7cac85e2-4bf7-42eb-a1ce-26dd4c61fe3d

 

ERROR RequestId:7cac85e2-4bf7-42eb-a1ce-26dd4c61fe3d Result:{"errorCode":-1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python3/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python3/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 172, in load_source\n    module = _load(spec)\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 675, in _load\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 655, in _load_unlocked\n  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 678, in exec_module\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 205, in _call_with_frames_removed\n  File \"/var/user/index.py\", line 9, in \u003cmodule\u003e\n    from lxml import etree\nModuleNotFoundError: No module named 'lxml'"} 

END RequestId: 7cac85e2-4bf7-42eb-a1ce-26dd4c61fe3d

Report RequestId: 7cac85e2-4bf7-42eb-a1ce-26dd4c61fe3d Duration:0ms Memory:128MB MemUsage:0.000000MB

**Comment by 1500931293** [comment]
用pycharm能运行 就是搞不懂云函数为啥不行

**Comment by mkdir700** [comment]
```
requests
lxml
BeautifulSoup4
apscheduler
```
需要安装这几个库
