### ISSUE TITLE
健康日报问题

### ISSUE THREAD

**Issue by pppunpkin** [mkdir700/chaoxing_auto_sign#40]
能问下健康日报打那个，12.2日后就算调用成功也打不上卡了，哪里出问题了吗，求大佬解释
返回结果：
{"msg": "请勿重复提交", "success": false}

调用成功日志：
START RequestId: d035ed14-c739-4e91-97e6-c92bc7d67ee7

Event RequestId: d035ed14-c739-4e91-97e6-c92bc7d67ee7

Starting new HTTPS connection (1): passport2.chaoxing.com:443

https://passport2.chaoxing.com:443 "GET /api/login?name=20170802003&pwd=hhh52552326&verify=0&schoolid=1762 HTTP/1.1" 200 212

{'uname': '20170802003', 'roleid': '3', 'opacPwd': False, 'realname': '好耶', 'result': True, 'uid': 127968065, 'dxfid': 3626, 'phone': '15625151145', 'schoolid': 39037, 'cxid': 127968065, 'email': '', 'isCertify': 1, 'status': '0'}

Starting new HTTP connection (1): office.chaoxing.com:80

http://office.chaoxing.com:80 "GET /data/web/apps/forms/fore/user/list?cpage=1&formId=7185&enc=f837c93e0de9d9ad82db707b2c27241e&formAppId= HTTP/1.1" 200 398671

http://office.chaoxing.com:80 "POST /data/apps/forms/fore/user/save?lookuid=127973522 HTTP/1.1" 200 43

 

END RequestId: d035ed14-c739-4e91-97e6-c92bc7d67ee7

Report RequestId: d035ed14-c739-4e91-97e6-c92bc7d67ee7 Duration:1061ms Memory:128MB MemUsage:61.300781MB

**Comment by mkdir700** [comment]
等我重新抓包看看

**Comment by pppunpkin** [comment]
> 等我重新抓包看看

谢谢大佬，辛苦了

**Comment by husky105** [comment]
超星的表单多了个验证，提交的表单中checkCode原来是空的，现在不是了

**Comment by pppunpkin** [comment]
> 超星的表单多了个验证，提交的表单中checkCode原来是空的，现在不是了
能问下怎么绕过验证吗..小白不懂

**Comment by mkdir700** [comment]
> 超星的表单多了个验证，提交的表单中checkCode原来是空的，现在不是了

可以给个抓包信息吗，换了手机没有root权限，模拟器抓包也有问题。

**Comment by pppunpkin** [comment]
> > 超星的表单多了个验证，提交的表单中checkCode原来是空的，现在不是了
> 
> 可以给个抓包信息吗，换了手机没有root权限，模拟器抓包也有问题。

不好意思不会抓包…我去学习一下。。。

**Comment by mkdir700** [comment]
我把手机root了，终于可以抓这个ssl pinning的数据包，和我猜想的一样。app没有更新，直接就新增了一个`checkOut`的字段，很有可能就是在js中添加了代码，抓包就看到了。`checkOut`字段是在后端生成后，随着响应来到前端，前端拿到之后再携带着相关参数请求提交日报的接口。
这就很明了了，
1. 在已登录的情况下`Get`请求`http://office.chaoxing.com/front/web/apps/forms/fore/apply?uid=127973604&code=l5RJsW2w&mappId=4545821&appId=1e354ddb52a743e88ed19a3704b1cf1a&appKey=127G2jhIhl05mw3S&id=7185&enc=f837c93e0de9d9ad82db707b2c27241e&state=39037&formAppId=&fidEnc=b06cba4a51ac2253`
2. 通过正则表达式提取`checkout`关键字
![image](https://user-images.githubusercontent.com/56359329/102156245-26281e00-3eb8-11eb-9caa-8b4e48e92e15.png)
3. 然后`post`请求提交健康日报的接口即可

**Comment by pppunpkin** [comment]
> 我把手机root了，终于可以抓这个ssl pinning的数据包，和我猜想的一样。app没有更新，直接就新增了一个`checkOut`的字段，很有可能就是在js中添加了代码，抓包就看到了。`checkOut`字段是在后端生成后，随着响应来到前端，前端拿到之后再携带着相关参数请求提交日报的接口。
> 这就很明了了，
> 
> 1. 在已登录的情况下`Get`请求`http://office.chaoxing.com/front/web/apps/forms/fore/apply?uid=127973604&code=l5RJsW2w&mappId=4545821&appId=1e354ddb52a743e88ed19a3704b1cf1a&appKey=127G2jhIhl05mw3S&id=7185&enc=f837c93e0de9d9ad82db707b2c27241e&state=39037&formAppId=&fidEnc=b06cba4a51ac2253`
> 2. 通过正则表达式提取`checkout`关键字
>    ![image](https://user-images.githubusercontent.com/56359329/102156245-26281e00-3eb8-11eb-9caa-8b4e48e92e15.png)
> 3. 然后`post`请求提交健康日报的接口即可

谢谢大佬，已经可用了，不过最后要注释掉才能执行，不太懂哈
def main_handler(event=None, context=None):
    # if event is not None:
    #     query: dict = event.get("queryString", "")
    #     if query:
    #         username, password, schoolid = query.get("name", ''), query.get("pwd", ''), query.get("schoolid", "")

    #         if not username or not password:
    #             return {
    #                 "message": "账号密码不能为空"
    #             }
    #         h = HeathReport(username=username, password=password, schoolid=schoolid)
    #         return h.daily_report()
    # h = HeathReport(username=USER_INFO['username'], password=USER_INFO['password'], schoolid=USER_INFO['schoolid'])
    h = HeathReport()
    return h.daily_report()


if __name__ == '__main__':
    print(main_handler())

**Comment by mkdir700** [comment]
> > 我把手机root了，终于可以抓这个ssl pinning的数据包，和我猜想的一样。app没有更新，直接就新增了一个`checkOut`的字段，很有可能就是在js中添加了代码，抓包就看到了。`checkOut`字段是在后端生成后，随着响应来到前端，前端拿到之后再携带着相关参数请求提交日报的接口。
> > 这就很明了了，
> > 
> > 1. 在已登录的情况下`Get`请求`http://office.chaoxing.com/front/web/apps/forms/fore/apply?uid=127973604&code=l5RJsW2w&mappId=4545821&appId=1e354ddb52a743e88ed19a3704b1cf1a&appKey=127G2jhIhl05mw3S&id=7185&enc=f837c93e0de9d9ad82db707b2c27241e&state=39037&formAppId=&fidEnc=b06cba4a51ac2253`
> > 2. 通过正则表达式提取`checkout`关键字
> >    ![image](https://user-images.githubusercontent.com/56359329/102156245-26281e00-3eb8-11eb-9caa-8b4e48e92e15.png)
> > 3. 然后`post`请求提交健康日报的接口即可
> 
> 谢谢大佬，已经可用了，不过最后要注释掉才能执行，不太懂哈
> def main_handler(event=None, context=None):
> # if event is not None:
> # query: dict = event.get("queryString", "")
> # if query:
> # username, password, schoolid = query.get("name", ''), query.get("pwd", ''), query.get("schoolid", "")
> 
> ```
> #         if not username or not password:
> #             return {
> #                 "message": "账号密码不能为空"
> #             }
> #         h = HeathReport(username=username, password=password, schoolid=schoolid)
> #         return h.daily_report()
> # h = HeathReport(username=USER_INFO['username'], password=USER_INFO['password'], schoolid=USER_INFO['schoolid'])
> h = HeathReport()
> return h.daily_report()
> ```
> 
> if **name** == '**main**':
> print(main_handler())

嗯 删掉就可以了，那个是给腾讯云函数用的
