### ISSUE TITLE
连接官方接口失败

### ISSUE THREAD

**Issue by nymanyim** [mkdir700/chaoxing_auto_sign#41]
2020-12-15 16:48:13,297 Traceback (most recent call last):
  File "/root/.pyenv/versions/3.7.8/lib/python3.7/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/root/.pyenv/versions/3.7.8/lib/python3.7/asyncio/base_events.py", line 962, in create_connection
    raise exceptions[0]
  File "/root/.pyenv/versions/3.7.8/lib/python3.7/asyncio/base_events.py", line 949, in create_connection
    await self.sock_connect(sock, address)
  File "/root/.pyenv/versions/3.7.8/lib/python3.7/asyncio/selector_events.py", line 473, in sock_connect
    return await fut
  File "/root/.pyenv/versions/3.7.8/lib/python3.7/asyncio/selector_events.py", line 503, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('42.62.107.178', 443)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./cloud_sign.py", line 356, in run
    result = await auto_sign.sign_tasks_run()
  File "./cloud_sign.py", line 275, in sign_tasks_run
    result: List[Optional[Dict]] = await asyncio.gather(*tasks)
  File "./cloud_sign.py", line 206, in get_activeid
    async with self.session.get(url) as resp:
  File "/root/.pyenv/versions/3.7.8/lib/python3.7/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/root/.pyenv/versions/3.7.8/lib/python3.7/site-packages/aiohttp/client.py", line 521, in _request
    req, traces=traces, timeout=real_timeout
  File "/root/.pyenv/versions/3.7.8/lib/python3.7/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/root/.pyenv/versions/3.7.8/lib/python3.7/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/root/.pyenv/versions/3.7.8/lib/python3.7/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/root/.pyenv/versions/3.7.8/lib/python3.7/site-packages/aiohttp/connector.py", line 1032, in _create_direct_connection
    client_error=client_error,
  File "/root/.pyenv/versions/3.7.8/lib/python3.7/site-packages/aiohttp/connector.py", line 975, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host mobilelearn.chaoxing.com:443 ssl:default [Connect call failed ('42.62.107.178', 443)]

linux用curl测试mobilelearn.chaoxing.com返回405，用php带值测试可以签到成功。大大这是咋回事呀

**Comment by nymanyim** [comment]
测试了下，改用http访问签到前端获取id，会跳转登陆页。用https访问前端页面，提示访问频繁，需要输入验证码。

**Comment by nymanyim** [comment]
始终获取不了最新签到，监控时间：3分钟。登录接口打印登录成功，cookies带入activeid任务id获取页面打印未登录跳转到了登录页面。疑似api脚本cookies问题。

**Comment by nymanyim** [comment]
{'JSESSIONID': {'expires': '', 'path': '/', 'comment': '', 'domain': 'passport2.cha
oxing.com', 'max-age': '', 'secure': '', 'httponly': True, 'version': '', 'samesite
': ''}, 'lv': {'expires': 'Fri, 15-Jan-2021 04:49:23 GMT', 'path': '/', 'comment': 
'', 'domain': 'chaoxing.com', 'max-age': '0', 'secure': '', 'httponly': '', 'versio
n': '1', 'samesite': ''}, 'fid': {'expires': 'Fri, 15-Jan-2021 04:49:23 GMT', 'path
': '/', 'comment': '', 'domain': 'chaoxing.com', 'max-age': '0', 'secure': '', 'htt
ponly': '', 'version': '1', 'samesite': ''}, '_uid': {'expires': 'Fri, 15-Jan-2021 
04:49:23 GMT', 'path': '/', 'comment': '', 'domain': 'chaoxing.com', 'max-age': '0'
, 'secure': '', 'httponly': '', 'version': '1', 'samesite': ''}, 'uf': {'expires': 
'Fri, 15-Jan-2021 04:49:23 GMT', 'path': '/', 'comment': '', 'domain': 'chaoxing.co
m', 'max-age': '0', 'secure': '', 'httponly': '', 'version': '1', 'samesite': ''}, 
'_d': {'expires': 'Fri, 15-Jan-2021 04:49:23 GMT', 'path': '/', 'comment': '', 'dom
ain': 'chaoxing.com', 'max-age': '0', 'secure': '', 'httponly': '', 'version': '1',
 'samesite': ''}, 'UID': {'expires': 'Fri, 15-Jan-2021 04:49:23 GMT', 'path': '/', 
'comment': '', 'domain': 'chaoxing.com', 'max-age': '0', 'secure': '', 'httponly': 
'', 'version': '1', 'samesite': ''}, 'vc': {'expires': 'Fri, 15-Jan-2021 04:49:23 G
MT', 'path': '/', 'comment': '', 'domain': 'chaoxing.com', 'max-age': '0', 'secure'
: '', 'httponly': True, 'version': '1', 'samesite': ''}, 'vc2': {'expires': 'Fri, 1
5-Jan-2021 04:49:23 GMT', 'path': '/', 'comment': '', 'domain': 'chaoxing.com', 'ma
x-age': '0', 'secure': '', 'httponly': True, 'version': '1', 'samesite': ''}, 'vc3'
: {'expires': 'Fri, 15-Jan-2021 04:49:23 GMT', 'path': '/', 'comment': '', 'domain'
: 'chaoxing.com', 'max-age': '0', 'secure': '', 'httponly': True, 'version': '1', '
samesite': ''}, 'xxtenc': {'expires': 'Fri, 15-Jan-2021 04:49:23 GMT', 'path': '/',
 'comment': '', 'domain': 'chaoxing.com', 'max-age': '0', 'secure': '', 'httponly':
 '', 'version': '1', 'samesite': ''}, 'DSSTASH_LOG': {'expires': 'Fri, 15-Jan-2021 
04:49:23 GMT', 'path': '/', 'comment': '', 'domain': 'chaoxing.com', 'max-age': '0'
, 'secure': '', 'httponly': '', 'version': '1', 'samesite': ''}, 'route': {'expires
': '', 'path': '/', 'comment': '', 'domain': 'passport2.chaoxing.com', 'max-age': '
', 'secure': '', 'httponly': '', 'version': '', 'samesite': ''}}  

验证cookies方法那儿直接返回False，从数据库获取的cookies打印是这样，还是无效。cookies_status为False时不会新保存登陆的cookies.

**Comment by nymanyim** [comment]
经过排查，发现是def check_cookies方法的问题，它获取的数据库返回的cookies是无效的，将从数据库取cookies修改为#cookies: dict = await self.mongo.get_cookie()。注释掉即可用第一次登陆时的cookies完成签到。
另外，该方法下的cookies验证是访问超星首页返回的http状态码判断的，200时应该是cookies无效，有效会返回304。
希望大大修改一下cookies的MongoDB获取机制，看不懂哈哈

**Comment by nymanyim** [comment]
进一步测试发现，根据状态码判断cookies行不通，加入无效cookies还是提示有效。另外大大可以考虑新增课程签到的情况，新增课程保存不了数据库，无法进行签到

**Comment by nymanyim** [comment]
之前注释太多了，没仔细看。#self.session.cookie_jar.update_cookies(cookies)，数据库得到的cookies无效是由这句引起的

**Comment by mkdir700** [comment]
感谢提出问题，看了你的测试

![image](https://user-images.githubusercontent.com/56359329/102330487-8e642600-3fc4-11eb-8fa7-81c52a97960f.png)

问题应该还是cookie是否有效的判断上

**Comment by nymanyim** [comment]
另外，这个无法通过cookies的前端网址，也就是存进数据库的无效cookies。不知道这时requests.session的cookies改变没，应该再利用session还是签到不了了

**Comment by nymanyim** [comment]
![QQ截图20201218143638](https://user-images.githubusercontent.com/54471703/102582903-87f9b980-413e-11eb-86b9-31da7cee1351.png)

**Comment by nymanyim** [comment]
大大，除了cookie的判断问题。不知道为啥存进数据库cookies消失了，在db_handler里最后一步存入cookies时打印出来都是正常的，存进去就没了，是不是mongo的问题哦？

**Comment by nymanyim** [comment]
发现cookies存入mongo错误的原因是由于不规则字典造成的，已修复cookie效验与存取问题，pull给大大了
