### ISSUE TITLE
健康日报后台更新

### ISSUE THREAD

**Issue by pppunpkin** [mkdir700/chaoxing_auto_sign#44]
大部分行失效，求大佬
返回数据:
{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 209, in main_handler\n    return h.daily_report()\n  File \"/var/user/index.py\", line 189, in daily_report\n    self._to_begin()\n  File \"/var/user/index.py\", line 172, in _to_begin\n    raw_data = self._get_last_heath_info()\n  File \"/var/user/index.py\", line 67, in _get_last_heath_info\n    raw_data = json.loads(resp.text)\n  File \"/var/lang/python3/lib/python3.6/json/__init__.py\", line 354, in loads\n    return _default_decoder.decode(s)\n  File \"/var/lang/python3/lib/python3.6/json/decoder.py\", line 339, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/var/lang/python3/lib/python3.6/json/decoder.py\", line 357, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)","statusCode":430}

日志:

START RequestId:4bdb42f1-67e9-4cf8-9090-8cb6b7b9b1e4

Starting new HTTPS connection (1): passport2.chaoxing.com:443

https://passport2.chaoxing.com:443 "GET /api/login?name=20170802003&pwd=hhh52552326&verify=0&schoolid=1762 HTTP/1.1" 302 192

Starting new HTTP connection (1): office.chaoxing.com:80

http://office.chaoxing.com:80 "GET /data/web/apps/forms/fore/user/list?cpage=1&formId=7185&enc=f837c93e0de9d9ad82db707b2c27241e&formAppId= HTTP/1.1" 302 192

Starting new HTTP connection (1): learn.chaoxing.com:80

http://learn.chaoxing.com:80 "GET /error_404.html HTTP/1.1" 200 554 

ERROR RequestId:4bdb42f1-67e9-4cf8-9090-8cb6b7b9b1e4 Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 209, in main_handler\n    return h.daily_report()\n  File \"/var/user/index.py\", line 189, in daily_report\n    self._to_begin()\n  File \"/var/user/index.py\", line 172, in _to_begin\n    raw_data = self._get_last_heath_info()\n  File \"/var/user/index.py\", line 67, in _get_last_heath_info\n    raw_data = json.loads(resp.text)\n  File \"/var/lang/python3/lib/python3.6/json/__init__.py\", line 354, in loads\n    return _default_decoder.decode(s)\n  File \"/var/lang/python3/lib/python3.6/json/decoder.py\", line 339, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/var/lang/python3/lib/python3.6/json/decoder.py\", line 357, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)","statusCode":430} 

END RequestId:4bdb42f1-67e9-4cf8-9090-8cb6b7b9b1e4

Report RequestId:4bdb42f1-67e9-4cf8-9090-8cb6b7b9b1e4 Duration:626ms Memory:128MB MemUsage:46.511719MB

**Comment by mkdir700** [comment]
前天更新了，是用的最新的脚本吗

**Comment by pppunpkin** [comment]
谢谢大佬，已解决
