### ISSUE TITLE
长时间挂机运行后出现如下提示

### ISSUE THREAD

**Issue by HolyDomain** [mkdir700/chaoxing_auto_sign#47]
Execution of job "local_ run (trigger: interval[0:05:00], next run at: 2021-03-02 08:08:59 EST)" skipped: maximum number of running instances reached (1)

**Comment by Vesugierii** [comment]
运行时间间隔放长一点

**Comment by HolyDomain** [comment]
> 运行时间间隔放长一点

这个是按照默认的五分钟出现的啊

**Comment by shanyan-wcx** [comment]
写一个脚本每隔一段时间删除logs.log就行了
