### ISSUE TITLE
感谢发布自动签到代码

### ISSUE THREAD

**Issue by Bell520vae** [mkdir700/chaoxing_auto_sign#5]
谢谢老哥了，，刚刚我测试，输入了手机号和密码，并没有登录成功，老是返回登录失败或者当前人数过多，自己手动get登录url可以登录成功，还请老哥优化一下，谢谢，我提个建议：去除学号登录，直接手机号加密码登录，毕竟更广泛，还有希望优化一下程序，我有更好的接口，可以签到所有，不用判断是哪种签到，希望老哥能带来一个更好的版本，希望能带来一个能挂在函数云上的版本，
链接: https://pan.baidu.com/s/1N9Ip4Qbw_lPO3jmzR2EfHA 提取码: Bell

程序运行：
手机号登录-获取所有课程id-获取所有活动列表签到id-get签到-程序结束。
希望再加上server酱实现签到成功消息通知！挂在函数云上，实现自动运行，（是个不错免费省事的方案）

哈哈哈，一不小心说了这么多，如果老哥愿意实现，那就拜托了，万分感谢！！！！

**Comment by Bell520vae** [comment]
当然，如果是用PHP写的话，我可以选择免费空间+云监控来实现。哈哈哈哈，也是个方便用户的方法。

**Comment by mkdir700** [comment]
感谢你的建议，我也是学生一枚，我还没接触过，云函数，看了下腾讯云有这个项目，我可以试试看，关于登录失败的问题，我正在看怎么回事，感谢反馈。

**Comment by Bell520vae** [comment]
感谢你老哥，等你试试腾讯云的云函数，你就会明白，这是一个很好的东西，差不多是免费vps服务器，

**Comment by Bell520vae** [comment]
貌似云函数上实现有点不靠谱了，，，超新星禁止腾讯和阿里云的ip访问，会导致403.。。。。。哎，，希望有PHP版本吧。。。这样可以挂免费空间。

**Comment by mkdir700** [comment]
哈哈，确实，还有一个腾讯云函数，好像不能创建新文件，或者创建的文件只有读权限，不能写。
我想保存cookies到cookies.json 文件，报错只读

**Comment by Bell520vae** [comment]
可能账号密码登录方式都需要修改，，我这挂的几个云函数的程序，大部分都是cookie登录，大概是因为方便，精简成一个文件吧，还有请求的时候不会每次都去获取cookie，超新星禁止腾讯云的ip，只能python的那什么r模块加代理，，，哎，，发现python和php才是好语言那，，，，

**Comment by mkdir700** [comment]
我试了，代理IP请求登录，但是还是不行。
我新加了cookies.json 文件，第一次登录会保存cookies
第二次登录则会先去验证cookies是否有效，有效就拿来用
无效，则重新登录，获取cookies并保存

**Comment by Bell520vae** [comment]
这个好，我现在也在折腾这个代理，，，，自己也搭建了http代理，如果需要的话我发你。自己不会python,所以我现在基本上在瞎倒腾

**Comment by Bell520vae** [comment]
刚刚测试了老哥发布的新版本，一次只签一个，并且重复签最先发布的一个，如果有多个签到不会去签多个（当然，不会出现多个签到同时出现），然后只能签普通和手势，二维和位置签到不了，，我那个分享的签到接口，四种签到一个接口都能签到，只是位置签到不会提交位置信息，，，，老哥加油，，，以上都不重要，目前只差代理了哈哈哈哈哈哈，还有一个好东西：Server酱：http://sc.ftqq.com/3.version   发送一个get请求微信那就能获得消息。

**Comment by mkdir700** [comment]
是的，我只做了普通签到和手势签到，我们学校只有这两个，要做其他的，我只能看别人的代码，没有测试账号。
多个课程签到，我之前测试了，多个课程是可以签到的，等机会再测试看。有可能是返回的结果只显示了一个，实质上都签了？

**Comment by Bell520vae** [comment]
哈哈哈哈，没事2种签到也够用了，可以找个同学借个账号，然后新建课程，把自己拉进去，然后发布签到，我目前就是这样测试的，，，哎，，，目前只想在云函数上运行，，，使用了代理老是报错，{"errorCode":-1,"errorMessage":"Task timed out after 10 seconds"}，，，也不知道为啥，好多作者都是用python写的，，我没有找到一个PHP的

**Comment by mkdir700** [comment]
。。。我不知道还可以自己创建课程这种操作，哈哈，我去试试，把二维码签到和位置签到搞出来
这个错误，应该就是代理IP之后，一直访问不了目标网站，然后延迟超过10秒报错了。

**Comment by Bell520vae** [comment]
哈哈哈哈，老哥加油哈哈哈，我分享的那个签到接口，4种签到全部能签，需要的参数好像也是一样的，并且会返回数据，如果签过了会返回已签到，成功签到返回ass什么来着英文，用来判断是否签到成功，还可以在加上一句签到成功get Sever酱的请求，来告诉用户签到成功，简直完美。。。我前面用的另一个老哥写的，然后修改了一下加了消息提醒，，，无奈学习通禁止腾讯云ip，，，我本地测试能行，不知道为啥一到腾讯云就报那个超时的错误。。

**Comment by 616161539** [comment]
可以做一个php的吗？腾讯云函数各种报错。。。

**Comment by mkdir700** [comment]
php没学过，你可以使用这个接口
http://101.89.182.58:9090/sign/

**Comment by Zxilly** [comment]
> 哈哈哈哈，老哥加油哈哈哈，我分享的那个签到接口，4种签到全部能签，需要的参数好像也是一样的，并且会返回数据，如果签过了会返回已签到，成功签到返回ass什么来着英文，用来判断是否签到成功，还可以在加上一句签到成功get Sever酱的请求，来告诉用户签到成功，简直完美。。。我前面用的另一个老哥写的，然后修改了一下加了消息提醒，，，无奈学习通禁止腾讯云ip，，，我本地测试能行，不知道为啥一到腾讯云就报那个超时的错误。。

腾讯云直接请求就会看到一个403，应该是IP拉黑了

**Comment by HuuLane** [comment]
github action 用 cron 来跑
