### ISSUE TITLE
当前版本签到成功不会返回成功提示

### ISSUE THREAD

**Issue by sudatime** [mkdir700/chaoxing_auto_sign#58]
只会返回
{
    "msg": 2000,
    "detail": "当前暂无签到任务"
}

**Comment by mkdir700** [comment]
是否执行了多次签到任务

**Comment by sudatime** [comment]
只有一个人，一次签到活动

**Comment by sudatime** [comment]
并且此版本与上个版本的MongoDB数据格式不同 会在
coroutine = self.get_activeid(i[1], i[0], i[2], client)   报错。
报错信息如下：
Traceback (most recent call last):
  File "D:\tools\demo\chaoxing_auto_sign\api\cloud_sign.py", line 278, in interface
    result = await auto_sign.start_sign_tasks(client)
  File "D:\tools\demo\chaoxing_auto_sign\api\cloud_sign.py", line 210, in start_sign_tasks
    coroutine = self.get_activeid(i[1], i[0], i[2], client)
KeyError: 1
解决方法是：删除原数据库数据

**Comment by sudatime** [comment]
`        async with self.session.request('GET',
                                        'https://mobilelearn.chaoxing.com/widget/sign/pcStuSignController/preSign',
                                        params=params, headers=self.headers, verify_ssl=False) as resp:
            assert resp.status == 200
            return {
                'date': time.strftime("%m-%d %H:%M", time.localtime()),
                'status': 3000
            }`
在执行此行之前就已经签到完成了
