### ISSUE TITLE
位置签到经纬度无效，定位一律显示中国

### ISSUE THREAD

**Issue by shanyan-wcx** [mkdir700/chaoxing_auto_sign#59]

**Comment by sudatime** [comment]
api/sign_request.py


`async def addr_sign(self):
        """位置签到"""
        params = {
            'name': '',
            'activeId': self.activeid,
            'address': '中国',
            'uid': '',
            'clientip': '0.0.0.0',
            'latitude': '-2',
            'longitude': '-1',
            'fid': '',
            'appType': '15',
            'ifTiJiao': '1'
        }`

其他地方自己找
