### ISSUE TITLE
希望能加入Server酱微信推送

### ISSUE THREAD

**Issue by sslspace** [mkdir700/chaoxing_auto_sign#6]
非常感谢开发者写了这么优秀的脚本，要是能添加上Server酱的微信推送就更完美了，签到成功后发送微信推送通知。

Server酱官网：http://sc.ftqq.com/3.version

另外控制台报 InsecureRequestWarning 产生大量无用日志，可以添加以下代码屏蔽它们：
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

**Comment by mkdir700** [comment]
感谢感谢，脚本已经更新了
- 加入server酱，签到消息推送至微信
- 纠正因证书问题，导致运行过程中，输出大量异常消息
- 优化签到类型的逻辑判断

**Comment by sslspace** [comment]
作者把自己的key给暴露啦！
<br>
更新后会发生错误：

cookies有效哦
Traceback (most recent call last):
  File "/root/qiandao/new/Caoxing_SignIn.py", line 308, in 
    print(local_run())
  File "/root/qiandao/new/Caoxing_SignIn.py", line 300, in local_run
    server_chan_send(result)
  File "/root/qiandao/new/Caoxing_SignIn.py", line 291, in server_chan_send
    requests.get(server_chan['url']+server_chan['sckey'], params=params)
KeyError: 'sckey'

当前课程情况为 有签到任务，但任务已经完成，也许是发送空的推送消息失败了？
很多人的需求是把脚本挂在服务器，每分钟运行一次，当签到成功时发送消息推送

**Comment by mkdir700** [comment]
又更新了下，你再试试看

**Comment by sslspace** [comment]
成功运行并收到推送，但是推送的是早上已经签到成功的科目

**Comment by mkdir700** [comment]
这个没考虑到，脚本做的判定是，进行中的，都是还未签到的。
我再优化下吧，每次签到成功了，就把签到成功的activeid记录下来。

**Comment by sslspace** [comment]
好的，谢谢你
