### ISSUE TITLE
运行报错module 'asyncio' has no attribute 'WindowsSelectorEventLoopPolicy'

### ISSUE THREAD

**Issue by shanyan-wcx** [mkdir700/chaoxing_auto_sign#61]
Job "start (trigger: interval[0:00:20], next run at: 2021-04-22 08:11:49 HKT)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "main.py", line 48, in start
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
AttributeError: module 'asyncio' has no attribute 'WindowsSelectorEventLoopPolicy'

**Comment by mkdir700** [comment]
https://github.com/MrYsLab/pymata-aio/issues/104

**Comment by Vesugierii** [comment]
> 104

这个解决办法没有效果 环境：python3.8

**Comment by Vesugierii** [comment]
> 
> 
> [MrYsLab/pymata-aio#104](https://github.com/MrYsLab/pymata-aio/issues/104)


这个解决办法没有效果 环境：python3.8

**Comment by olig48** [comment]
我也遇到了，现在还是用上个版本的代码吧

**Comment by mkdir700** [comment]
> 我也遇到了，现在还是用上个版本的代码吧

Linux还是Windows

**Comment by olig48** [comment]
> > 我也遇到了，现在还是用上个版本的代码吧
> 
> Linux还是Windows

linux

**Comment by mkdir700** [comment]
好的，明白了
