### ISSUE TITLE
本地签到任务执行完毕后，统一发送消息

### ISSUE THREAD

**Issue by jack331200** [mkdir700/chaoxing_auto_sign#67]
ok,感谢.
有个使用中的小小疑惑: 我一共接受到的信息是一起发送过来的,这些信息无法分别是哪些账号的.

_Originally posted by @jack331200 in https://github.com/mkdir700/chaoxing_auto_sign/issues/66#issuecomment-830812130_

**Comment by jack331200** [comment]
好像又了点小问题,发送消息的问题,
在server酱上只能接收到没有签到的消息,签到成功的消息无法接受,但是实际上我定时任务执行的脚本是生效的.

**Comment by mkdir700** [comment]
> 好像又了点小问题,发送消息的问题,
> 在server酱上只能接收到没有签到的消息,签到成功的消息无法接受,但是实际上我定时任务执行的脚本是生效的.

我有空看看

**Comment by mkdir700** [comment]
https://github.com/mkdir700/chaoxing_auto_sign/releases/tag/v0.0.2
