### ISSUE TITLE
ModuleNotFoundError: No module named 'click'

### ISSUE THREAD

**Issue by mkdir700** [mkdir700/chaoxing_auto_sign#70]
import click
ModuleNotFoundError: No module named 'click'
报这个错怎么解决啊？跟这个click模块有关

_Originally posted by @bigoceans in https://github.com/mkdir700/chaoxing_auto_sign/issues/69#issuecomment-848642441_

**Comment by mkdir700** [comment]
执行以下代码，安装所需依赖后运行。
```python
pip install requirements.txt
```

**Comment by bigoceans** [comment]
收到，多谢大佬

**Comment by bigoceans** [comment]
> 执行以下代码，安装所需依赖后运行。
> 
> ```python
> pip install requirements.txt
> ```

我在local目录下执行了pip install requirements.txt
控制台报错：
ERROR: Could not find a version that satisfies the requirement requirements.txt (from versions: none)
ERROR: No matching distribution found for requirements.txt
求助

**Comment by 9cats** [comment]
应该是输入以下指令吧

> pip install -r requirements.txt

**Comment by bigoceans** [comment]
> > 执行以下代码，安装所需依赖后运行。
> > ```python
> > pip install requirements.txt
> > ```
> 
> 我在local目录下执行了pip install requirements.txt
> 控制台报错：
> ERROR: Could not find a version that satisfies the requirement requirements.txt (from versions: none)
> ERROR: No matching distribution found for requirements.txt
> 求助

我知道了加个-r 就好了

**Comment by bigoceans** [comment]
> 应该是输入以下指令吧
> 
> > pip install -r requirements.txt

是的没错，谢谢啦
