### ISSUE TITLE
拍照签到怎么换照片？

### ISSUE THREAD

**Issue by XiaoliChan** [mkdir700/chaoxing_auto_sign#9]
如题

**Comment by mkdir700** [comment]
post 请求https://pan-yz.chaoxing.com/upload?_token=5d2e8d0aaa92e3701398035f530c4155
参数
puid：80421235
file：文件
Python请求示例代码
```Python
import requests

url = "https://pan-yz.chaoxing.com/upload?_token=5d2e8d0aaa92e3701398035f530c4155"

payload = {'puid': '80421235'}
files = [
  ('file', open('/home/mk/Desktop/123.jpeg','rb'))
]
headers = {
  'Cookie': 'route=0a371e20663fc5318adffbeed948add0'
}

response = requests.request("POST", url, headers=headers, data = payload, files = files)

print(response.text.encode('utf8'))
```
返回结果
```
{"result":true,"msg":"success","puid":80421235,"data":{"filetype":"","extinfo":"","thumbnail":"http://pan-yz.chaoxing.com/thumbnail/origin/361a2be086dd4566af250de149470c61?type=img","creator":80421235,"modifyDate":1585010884196,"resTypeValue":3,"sort":0,"suffix":"jpeg","resid":449131457835950080,"topsort":0,"restype":"RES_TYPE_NORMAL","duration":0,"pantype":"USER_PAN","puid":80421235,"size":23187,"uploadDate":1585010884196,"filepath":"","crc":"feb2b91fbf57a3cd41504afa40add6c5","isfile":true,"name":"123.jpeg","residstr":"449131457835950080","objectId":"361a2be086dd4566af250de149470c61"},"crc":"feb2b91fbf57a3cd41504afa40add6c5","resid":449131457835950080,"objectId":"361a2be086dd4566af250de149470c61"}
```
只需要最后面这一个`"objectId":"361a2be086dd4566af250de149470c61"`
将objectid的值，填入到原脚本的objectid

**Comment by XiaoliChan** [comment]
> post 请求https://pan-yz.chaoxing.com/upload?_token=5d2e8d0aaa92e3701398035f530c4155
> 参数
> puid：80421235
> file：文件
> Python请求示例代码
> 
> ```python
> import requests
> 
> url = "https://pan-yz.chaoxing.com/upload?_token=5d2e8d0aaa92e3701398035f530c4155"
> 
> payload = {'puid': '80421235'}
> files = [
>   ('file', open('/home/mk/Desktop/123.jpeg','rb'))
> ]
> headers = {
>   'Cookie': 'route=0a371e20663fc5318adffbeed948add0'
> }
> 
> response = requests.request("POST", url, headers=headers, data = payload, files = files)
> 
> print(response.text.encode('utf8'))
> ```
> 
> 返回结果
> 
> ```
> {"result":true,"msg":"success","puid":80421235,"data":{"filetype":"","extinfo":"","thumbnail":"http://pan-yz.chaoxing.com/thumbnail/origin/361a2be086dd4566af250de149470c61?type=img","creator":80421235,"modifyDate":1585010884196,"resTypeValue":3,"sort":0,"suffix":"jpeg","resid":449131457835950080,"topsort":0,"restype":"RES_TYPE_NORMAL","duration":0,"pantype":"USER_PAN","puid":80421235,"size":23187,"uploadDate":1585010884196,"filepath":"","crc":"feb2b91fbf57a3cd41504afa40add6c5","isfile":true,"name":"123.jpeg","residstr":"449131457835950080","objectId":"361a2be086dd4566af250de149470c61"},"crc":"feb2b91fbf57a3cd41504afa40add6c5","resid":449131457835950080,"objectId":"361a2be086dd4566af250de149470c61"}
> ```
> 
> 只需要最后面这一个`"objectId":"361a2be086dd4566af250de149470c61"`
> 将objectid的值，填入到原脚本的objectid

ok，话说，使用这个脚本，会不会被ban号啊

**Comment by XiaoliChan** [comment]
话说，使用你的脚本设置crontab，这样定时签到会不会被ban

**Comment by mkdir700** [comment]
我自己也在用，目前没啥问题

**Comment by XiaoliChan** [comment]
> 我自己也在用，目前没啥问题

另外一个项目“AutoCheckIn”的作者写到：“检测所有课程是否有签到任务。慎用，使用次数过多可能会被学习通拉入黑名单。”，所以就有点害怕了

**Comment by mkdir700** [comment]
我设置的是每10分钟自动签到一次

**Comment by XiaoliChan** [comment]
*/10 8-22 * * * root python3 /home/xiaoli/chaoxing_auto_sign/cloud_sign.py >> /tmp/sign.txt
我也是这样设置的，不知道会不会频率太高了

**Comment by qcnhy** [comment]
搞个黑色的图还说 网络原因没传上去 搞个头像就有点。。。

**Comment by Ircon** [comment]
请问一下默认的，如果不修改代码，代码中的那个照片是啥？

**Comment by mkdir700** [comment]
是一个吴彦祖的头像

**Comment by Ircon** [comment]
> 是一个吴彦祖的头像

好吧，我换一下。我们老师比较较真。

**Comment by mkdir700** [comment]
头像自定义，还在做，之前在搞多用户多任务签到

**Comment by Ircon** [comment]
> 头像自定义，还在做，之前在搞多用户多任务签到

加油。之前自己也想做一个，打算模拟网页端。最后发现网上有，就放弃了。😂

**Comment by qcnhy** [comment]
微信公众号 “海经校园” 关注发送“学习通自动签到”。有人家做好的平台------------------ 原始邮件 ------------------
发件人: "Ircon"<notifications@github.com>
发送时间: 2020年4月18日(星期六) 下午5:01
收件人: "mkdir700/chaoxing_auto_sign"<chaoxing_auto_sign@noreply.github.com>;
抄送: "qcnhy"<qcnhy@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [mkdir700/chaoxing_auto_sign] 拍照签到怎么换照片？ (#9)




  
头像自定义，还在做，之前在搞多用户多任务签到
  
加油。之前自己也想做一个，打算模拟网页端。最后发现网上有，就放弃了。
 
&mdash;

**Comment by mkdir700** [comment]
可以自己做着玩，不一定别人做了，自己就不做了，练习练习

**Comment by Ircon** [comment]
我是为了应付老师，我这几天在忙着其他的事。我们老师比较较真，我怕开学因为签到这事学校又搞我们。😂用其他平台不如自己服务器安心。

**Comment by qcnhy** [comment]
是的，赞同你的观点------------------ 原始邮件 ------------------
发件人: "Ircon"<notifications@github.com>
发送时间: 2020年4月18日(星期六) 下午5:46
收件人: "mkdir700/chaoxing_auto_sign"<chaoxing_auto_sign@noreply.github.com>;
抄送: "qcnhy"<qcnhy@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [mkdir700/chaoxing_auto_sign] 拍照签到怎么换照片？ (#9)




 
我是为了应付老师，我这几天在忙着其他的事。我们老师比较较真，我怕开学因为签到这事学校又搞我们。用其他平台不如自己&#x670D;务器安心。
 
&mdash;

**Comment by qcnhy** [comment]
我是为了满足自我需要，别人有了我就直接用了哈哈------------------ 原始邮件 ------------------
发件人: "mkdir700"<notifications@github.com>
发送时间: 2020年4月18日(星期六) 下午5:43
收件人: "mkdir700/chaoxing_auto_sign"<chaoxing_auto_sign@noreply.github.com>;
抄送: "qcnhy"<qcnhy@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [mkdir700/chaoxing_auto_sign] 拍照签到怎么换照片？ (#9)




 
可以自己做着玩，不一定别人做了，自己就不做了，练习练习
 
&mdash;
